# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pvz.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pvz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpvz.proto\x12\x03pvz\"\x13\n\x11GetPVZListRequest\":\n\x03PVZ\x12\n\n\x02id\x18\x01 \x01(\t\x12\x19\n\x11registration_date\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\",\n\x12GetPVZListResponse\x12\x16\n\x04pvzs\x18\x01 \x03(\x0b\x32\x08.pvz.PVZ2K\n\nPVZService\x12=\n\nGetPVZList\x12\x16.pvz.GetPVZListRequest\x1a\x17.pvz.GetPVZListResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pvz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_GETPVZLISTREQUEST']._serialized_start=18
  _globals['_GETPVZLISTREQUEST']._serialized_end=37
  _globals['_PVZ']._serialized_start=39
  _globals['_PVZ']._serialized_end=97
  _globals['_GETPVZLISTRESPONSE']._serialized_start=99
  _globals['_GETPVZLISTRESPONSE']._serialized_end=143
  _globals['_PVZSERVICE']._serialized_start=145
  _globals['_PVZSERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
